language: node_js
node_js:
- 8.11.3
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
  code_climate:
    repo_token: adb05218d78367e7266a3de667450489f72c1b1ac00c1cbcbe3f28b0402b219b
deploy:
  provider: npm
  email: technique@yocto.re
  api_key:
    secure: AdwH6P2Yqe9JjwX9w5ReijmcN77fZQFpYL80ZH4KS1s+P9ELO/NBeao2pV4RJbBR/erjIiE1mFSr65UlGumSeZaUls775w4UVIV2EIp+24zGibVkfaJeWuy+T3DwyFT6k7zc0vLwpax/AGW5JbWlPwbKJftFnskWqiyI/95y2weMzR39hosB/N0OgxJRxvg9Ffzn0g1jLF+CpYWJoTj1m1WE0dLARIsnTCXmb725Tji8t4OUSn64viVL7/0nsFKVx/MJzG6Qr1S6h2ZdEDl3vCVHzbIQ/fP8W8JP3Vfk9NrDEGfDCAnjWKMODG5RdKmvi1VkgYnvWjlA8jMOZZrk2wPRB+IXyU+/+ntO5S/Jf+Vt0PXgeWzih3vHIhBqJxeVEd4PbXKBOz90uDKb1/iNteYYWdkc0TADSOPK1ZTKdRwd6ZVCwyt8sRnF8uSPJk4Dn9Vlc7uy3JDRBfZxClYgRgcJ3jBMpG4XIh0LB9pnjBuNihuQb1uLOo+lQNUwLUceJ9UYOMFzzyacnwsm1gKLu17tOc8RhBPGNBQgt/0fwpH1sQRvMEH881CR48VaSwZ8GZ0MYsM2leCczpz45H11vUDW+b3g2nIiccwzxuimv/Z4kbjZEJ0cRUYk7k5NGSYnM0Pv4bAHBYuBFRI3om78pXgEU0TgWPA/DGEnJLx0CwQ=
  on:
    tags: true
    repo: yoctore/yocto-doc
before_install: npm install -g grunt-cli
install: npm install
